### ISSUE TITLE
Fix vulnerability in db journal

### ISSUE THREAD

**Issue by borkurdotnet** [FutureCitiesCatapult/TomboloDigitalConnector#140]
Say we have dataset X containing timed values for lsoas and msoas.

We run an experiment for looking at X for all msoas. I.e.
- We load msoas.
- We load X and assigning values to all msoas.

We are happy!

We run an experiment for looking at X for all lsoas. I.e.
- We load lsoas.
- We do not load X because the DBJournal says that X is already loaded.

We are not happy because the system exports no values for lsoas.

**Comment by lorenaqendro** [comment]
Not an issue anymore.
