### ISSUE TITLE
Marking up reading order on Wiki

### ISSUE THREAD

**Issue by borkurdotnet** [FutureCitiesCatapult/TomboloDigitalConnector#256]
Although wikis are designed not to have a reading order relation between pages, we do have one for the current version of the documentation. This creates some open questions:

- Would it be a good idea to enumerate the Table of contents to suggest an order of reading?
- Would it be helpful to add a ‘next’ link at the bottom of each page so that people can flow through the wiki?

**Comment by lorenaqendro** [comment]
This issue can be closed as we do not have a wiki anymore and the documentation is in the code base.
