### ISSUE TITLE
Wiki image resolution

### ISSUE THREAD

**Issue by borkurdotnet** [FutureCitiesCatapult/TomboloDigitalConnector#257]
Update the wiki images with higher resolution version.

At the moment we do not have the wiki accessible for non-github users and therefore need to automatically export a pdf version. For this, high resolution images are a problem. As soon as we open up the digital connector we can replace the images with higher resolution since the pdf export will be obsolete.

**Comment by lorenaqendro** [comment]
This issue can be closed as the images have an acceptable resolution now.
