### ISSUE TITLE
Re-introduce the different between Field and a SingleValueField

### ISSUE THREAD

**Issue by borkurdotnet** [FutureCitiesCatapult/TomboloDigitalConnector#288]
When in the latest changes to AbstractField we effectively remove the difference between Field and SingleValueField, effectively making all fields a SingleValueField. This means that we cannot effectively make a difference between time series and single values. In addition, we have included an AttributeMatcher and and Attribute in the AbstractField which should not be there since not all fields have an attribute associated to them. 

In sum:

- We need to remove the SingleValueField implementation of the AbstractField and introduce an AbstractSingleValueField if needed.
- We need to move the AttributeMatcher and Attribute variables to a suitable abstract class so that it is used only in fields where an attribute variable makes sense.

**Comment by lorenaqendro** [comment]
@arya-hemanshu I think this issue can be closed, right?
