### ISSUE TITLE
JSON formatting as a Utils class

### ISSUE THREAD

**Issue by borkurdotnet** [FutureCitiesCatapult/TomboloDigitalConnector#301]
Make sure that all fields have a consistent JSON format by moving JSON generation to a Utils class.

The three JSON formats are:

```
label: value
label: {"timestamp":timestamp, "value":value}
label: [{"timestamp":timestamp, "value":value}, ...]
```

The util has a function (something like)

```
JSONObject getJsonObject(Boolean timestamp, Field field)
```

In order to distinguish between TimedValues and FixedValues the following method should be added to the SingleValueField interface:

```
LocalDateTime getTimestamp()
```

Make sure that this is thoroughly tested in fields.

**Comment by lorenaqendro** [comment]
This issue can be closed as #355 was open to cover the refactoring.
