### ISSUE TITLE
Move Wiki to documentation folder

### ISSUE THREAD

**Issue by borkurdotnet** [FutureCitiesCatapult/TomboloDigitalConnector#327]
Moving wiki to the main source code would allow to: 

- [ ] keep it up-to-date in line with the code
- [ ] create pull requests to suggest changes
- [ ] quantify commit to feel better at the end of the day

**Comment by lorenaqendro** [comment]
![high-level-system-architecture](https://user-images.githubusercontent.com/14051876/33561208-f87e3b5e-d909-11e7-8309-a6a7edd0e941.png)
![london-cycle-counts](https://user-images.githubusercontent.com/14051876/33561209-f8a01814-d909-11e7-87ba-1483ac3c5e9a.png)
![london-no2-concentration](https://user-images.githubusercontent.com/14051876/33561210-f8bdac4e-d909-11e7-932e-b21504abdb40.png)
![tombolo-erd](https://user-images.githubusercontent.com/14051876/33561211-f8d7412c-d909-11e7-9785-10fa91dae980.png)
![tutorial-london-cycle-counts-backoff](https://user-images.githubusercontent.com/14051876/33561212-f8eef47a-d909-11e7-8009-645ac58da5fa.png)
![tutorial-london-cycle-counts-la](https://user-images.githubusercontent.com/14051876/33561213-f9071faa-d909-11e7-98df-a8edae0c3a6a.png)
![tutorial-london-cycle-counts-lsoa](https://user-images.githubusercontent.com/14051876/33561215-f91ff0b6-d909-11e7-9d20-53e9c59ee0e5.png)
![use-cases-connector](https://user-images.githubusercontent.com/14051876/33561216-f975a8ee-d909-11e7-8729-d7eec6ae7e6f.png)

**Comment by lorenaqendro** [comment]
[annotatedRecipe.pdf](https://github.com/FutureCitiesCatapult/TomboloDigitalConnector/files/1543564/annotatedRecipe.pdf)
