### ISSUE TITLE
Rewrite main readme page including links to documentation

### ISSUE THREAD

**Issue by borkurdotnet** [FutureCitiesCatapult/TomboloDigitalConnector#328]
Rearrange content.

**Comment by lorenaqendro** [comment]
![final_output](https://user-images.githubusercontent.com/14051876/33429677-b8fc5796-d5c5-11e7-8dd3-159bbb657200.png)
![layer_properties_final_options](https://user-images.githubusercontent.com/14051876/33429678-b9198b5e-d5c5-11e7-86fd-71f7c866d519.png)
![layers_panel](https://user-images.githubusercontent.com/14051876/33429679-b930f1c2-d5c5-11e7-96e0-9ca338ad69fa.png)
![osm_menu_option](https://user-images.githubusercontent.com/14051876/33429681-b9512d02-d5c5-11e7-8539-e311a38cb55d.png)
![output_in_png](https://user-images.githubusercontent.com/14051876/33429682-b96d18f0-d5c5-11e7-8ca5-b86f0eaa7376.png)
![output_without_bg_map](https://user-images.githubusercontent.com/14051876/33429683-b985b7f2-d5c5-11e7-9855-83e4b8adc094.png)
![plugin_option_menu](https://user-images.githubusercontent.com/14051876/33429684-b99d00c4-d5c5-11e7-8f34-f39631017f9a.png)
![plugins_search](https://user-images.githubusercontent.com/14051876/33429685-b9b9a22e-d5c5-11e7-926b-4cd370aa4d6f.png)
![plugins_window](https://user-images.githubusercontent.com/14051876/33429686-b9d10658-d5c5-11e7-8a3b-0d4d204422da.png)
![projection_option](https://user-images.githubusercontent.com/14051876/33429687-b9e95d8e-d5c5-11e7-893a-1d719fda620d.png)
![projection_search](https://user-images.githubusercontent.com/14051876/33429688-ba026306-d5c5-11e7-9f88-4f93e00f8884.png)
![raw_output_uk_projection](https://user-images.githubusercontent.com/14051876/33429689-ba1e5066-d5c5-11e7-8816-32ae9ba7ead5.png)
![raw_output](https://user-images.githubusercontent.com/14051876/33429690-ba36cb8c-d5c5-11e7-97d6-a3da8b917eb2.png)
![dc_animation](https://user-images.githubusercontent.com/14051876/33429706-cf9edfdc-d5c5-11e7-9cff-f57e9b85f097.gif)
![tombolo_logo_trans_01](https://user-images.githubusercontent.com/14051876/33429707-cfb56b9e-d5c5-11e7-95e2-2b1acc3f173b.png)

**Comment by lorenaqendro** [comment]
[annotatedRecipe.pdf](https://github.com/FutureCitiesCatapult/TomboloDigitalConnector/files/1548320/annotatedRecipe.pdf)
