### ISSUE TITLE
Write Service Level Agreement

### ISSUE THREAD

**Issue by borkurdotnet** [FutureCitiesCatapult/TomboloDigitalConnector#331]

**Comment by lorenaqendro** [comment]
Not sure we actually need this given the licence.

**Comment by lorenaqendro** [comment]
@futureofjon do we need this?

**Comment by futureofjon** [comment]
Does it mean that we provide a minimum service level agreement to our users? If so, then no because we cannot guarantee it with our available resources unfortunately.

**Comment by lorenaqendro** [comment]
I believe that this part is clear in the licence, so I will close the issue.
