### ISSUE TITLE
Conflicting output file path for Catalogue and Exporter

### ISSUE THREAD

**Issue by arya-hemanshu** [FutureCitiesCatapult/TomboloDigitalConnector#340]
Gradle takes parameters for exportCatalogue and runExport command, both tasks expects outfile path, and having the same variable name is creating conflicts when webcomponents trying to execute the task from another process.

Need to change the variable name of catalogue exporter argument

**Comment by lorenaqendro** [comment]
Closing as it was solved in #347.
