### ISSUE TITLE
Avoid new instance of DownloadUtils in CensusImporter

### ISSUE THREAD

**Issue by borkurdotnet** [FutureCitiesCatapult/TomboloDigitalConnector#354]
### Description
In the `getSeedData()` function in the `CensusImporter` a new instance of `DownloadUtils` is created. As far as I know this is done since the local `downloadUtils` variable is null at this point in the code. It would be debugged and fixed why the variable is null at that point. When that is done we should use the non-null local variable. 

The main rationale for fixing this is to make sure that the seed data is downloaded in the configurable download directory but not in the constant `/tmp` as defined by this function.

### Error log
```
N/A
```

**Comment by arya-hemanshu** [comment]
fixed and merged
