### ISSUE TITLE
Add user Eddie to organisation

### ISSUE THREAD

**Issue by eddiejaoude** [FutureCitiesCatapult/TomboloDigitalConnector#364]
- [x] Remove user from repo collaborator
- [x] Add user to organisation with same privileges on repo

Then he can add it to his profile page...

<img width="1002" alt="screenshot 2017-12-01 07 59 01" src="https://user-images.githubusercontent.com/624760/33473250-89a23db4-d66d-11e7-9fc1-13e754d1efb3.png">

**Comment by lorenaqendro** [comment]
This issue can be closed as both points have bee addressed.

**Comment by eddiejaoude** [comment]
Public on my profile 🤓 ...

<img width="1043" alt="screenshot 2017-12-05 05 45 41" src="https://user-images.githubusercontent.com/624760/33591819-a05b4432-d97f-11e7-93dc-71661898c368.png">

**Comment by eddiejaoude** [comment]
@lorenaqendro just to make you aware, I can see more repos now than before.

**Comment by lorenaqendro** [comment]
@eddiejaoude thanks! I changed it now. Please let me know if you can still see other repos.

**Comment by eddiejaoude** [comment]
@lorenaqendro strangely I still can 😕

**Comment by lorenaqendro** [comment]
@eddiejaoude it should be fixed now. Can you confirm please?

**Comment by eddiejaoude** [comment]
@lorenaqendro all looks good 👍
