### ISSUE TITLE
Organisation members (users) to have a profile picture

### ISSUE THREAD

**Issue by eddiejaoude** [FutureCitiesCatapult/TomboloDigitalConnector#366]
They will seem less like bots / fake users 🤓

Users:

- [x] https://github.com/aisnichon
- [x] https://github.com/arya-hemanshu
- [x] https://github.com/CharlHutton
- [x] https://github.com/thanosbnt

<img width="1013" alt="screenshot 2017-12-01 07 54 04" src="https://user-images.githubusercontent.com/624760/33473329-ec3736f0-d66d-11e7-91cc-f2cdaf78e1b8.png">

<img width="1008" alt="screenshot 2017-12-01 07 54 14" src="https://user-images.githubusercontent.com/624760/33473392-30a5a754-d66e-11e7-9f2d-4be791d2a959.png">

**Comment by lorenaqendro** [comment]
And... 
here they are, not anonymous anymore:

<img width="302" alt="screen shot 2018-01-05 at 10 59 14" src="https://user-images.githubusercontent.com/14051876/34606499-8f093482-f207-11e7-92d0-634aef700499.png">

**Comment by eddiejaoude** [comment]
Cool 👍
