### ISSUE TITLE
Organsation members to use 2FA

### ISSUE THREAD

**Issue by eddiejaoude** [FutureCitiesCatapult/TomboloDigitalConnector#367]
Organisation / repo and users are going to get more attention, best to require all members to have 2FA

Documentation https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/ 

<img width="717" alt="screenshot 2017-12-01 08 05 03" src="https://user-images.githubusercontent.com/624760/33473435-5b3ce64e-d66e-11e7-833c-2db04f990d03.png">

**Comment by lorenaqendro** [comment]
Closing as the members have now 2FA.
