### ISSUE TITLE
Use only markdown in the README

### ISSUE THREAD

**Issue by eddiejaoude** [FutureCitiesCatapult/TomboloDigitalConnector#369]
This is just a personal preference, but I suggest trying to keep the `*.md` files to markdown only. I appreciate more customisation can be achieved by putting `html` in there, however it makes it more complicated for others to update.

https://github.com/FutureCitiesCatapult/TomboloDigitalConnector/pull/363/files#diff-04c6e90faac2675aa89e2176d2eec7d8R4

**Comment by sassalley** [comment]
Happy to remove this - just figured that centreing the images is more visually appealing and wasn't sure if one could do that with Github flavoured markdown?

**Comment by eddiejaoude** [comment]
Unfortunately, GitHub flavoured markdown does not support text alignment. If you wish to keep it centred then the `html` will be required.

This is just a personal preference 🤓

**Comment by lorenaqendro** [comment]
![digital-connector-icon](https://user-images.githubusercontent.com/14051876/34300521-c74ced0a-e728-11e7-9f1a-fa233a987750.png)

**Comment by lorenaqendro** [comment]
Solved in #415 #417.
