### ISSUE TITLE
Create a release in GitHub

### ISSUE THREAD

**Issue by eddiejaoude** [FutureCitiesCatapult/TomboloDigitalConnector#370]
Manually creating them is fine for now.

*Note: In the future it would be good for CI to create `RC`s and push them back to GitHub*

<img width="1000" alt="screenshot 2017-12-01 08 07 29" src="https://user-images.githubusercontent.com/624760/33473530-b11184a8-d66e-11e7-94b9-447c227e5e59.png">

**Comment by lorenaqendro** [comment]
<img width="1025" alt="screen shot 2018-01-04 at 18 11 23" src="https://user-images.githubusercontent.com/14051876/34577874-bb88771c-f17a-11e7-8df1-2ef2f3ac56ed.png">

**Comment by eddiejaoude** [comment]
👍

**Comment by lorenaqendro** [comment]
> *Note: In the future it would be good for CI to create `RC`s and push them back to GitHub*

Created #423 for this.
