### ISSUE TITLE
Remove old branches

### ISSUE THREAD

**Issue by eddiejaoude** [FutureCitiesCatapult/TomboloDigitalConnector#371]
<img width="997" alt="screenshot 2017-12-01 07 29 16" src="https://user-images.githubusercontent.com/624760/33472273-6e87d196-d669-11e7-91a3-2d5e88af2e58.png">

**Comment by lorenaqendro** [comment]
Closing as stale and merged branches were removed.

**Comment by eddiejaoude** [comment]
Looking good 👍 

<img width="1005" alt="screenshot 2017-12-08 14 58 08" src="https://user-images.githubusercontent.com/624760/33771235-3e6f8bce-dc28-11e7-940e-a8ca42b373db.png">
