### ISSUE TITLE
upload windows tutorial images

### ISSUE THREAD

**Issue by arya-hemanshu** [FutureCitiesCatapult/TomboloDigitalConnector#372]
### Description
upload windows tutorial images

### Error log
No error

**Comment by arya-hemanshu** [comment]
![pg_create_database_tombolo](https://user-images.githubusercontent.com/19670372/33480393-a19258ee-d688-11e7-8f8d-7bb9c38f29a5.png)
![check_pwd](https://user-images.githubusercontent.com/19670372/33480395-a1afea4e-d688-11e7-961e-c93e1d2f9c24.png)
![cmd_run_admin](https://user-images.githubusercontent.com/19670372/33480396-a1c7862c-d688-11e7-883a-d78801411e5a.png)
![cp_check_for_postgres](https://user-images.githubusercontent.com/19670372/33480397-a1de3f48-d688-11e7-9545-2475db426231.png)
![env_screen](https://user-images.githubusercontent.com/19670372/33480398-a1f5fb06-d688-11e7-94d5-52084acfc562.png)
![git_clone_1](https://user-images.githubusercontent.com/19670372/33480399-a20dbd86-d688-11e7-82bf-c035770ee56e.png)
![git_cloning_tombolo](https://user-images.githubusercontent.com/19670372/33480400-a2396af8-d688-11e7-9309-5967c32faa63.png)
![git_download_1](https://user-images.githubusercontent.com/19670372/33480401-a250b5aa-d688-11e7-90fc-29d206406e01.png)
![git_installation_1](https://user-images.githubusercontent.com/19670372/33480402-a2682e60-d688-11e7-875b-3c2e7f56caa4.png)
![git_installation_2](https://user-images.githubusercontent.com/19670372/33480403-a281eec2-d688-11e7-81bf-89ad1ae1d08e.png)
![git_installation_3](https://user-images.githubusercontent.com/19670372/33480404-a298b5c6-d688-11e7-8fae-4553d37048f9.png)
![git_installation_4](https://user-images.githubusercontent.com/19670372/33480405-a2af30f8-d688-11e7-8431-b072f958b9c1.png)
![git_installation_5](https://user-images.githubusercontent.com/19670372/33480406-a2c677ae-d688-11e7-8f9a-88073a622312.png)
![git_installation_6](https://user-images.githubusercontent.com/19670372/33480407-a2df9af4-d688-11e7-9114-93abfad81b95.png)
![git_installation_7](https://user-images.githubusercontent.com/19670372/33480408-a2f7d9d4-d688-11e7-8042-7df70bbe6be0.png)
![git_installation_8](https://user-images.githubusercontent.com/19670372/33480409-a30edee0-d688-11e7-8388-92fb2ddf84b0.png)
![git_installation_9](https://user-images.githubusercontent.com/19670372/33480410-a326390a-d688-11e7-9a22-fab991b4dbcf.png)
![git_installation_10](https://user-images.githubusercontent.com/19670372/33480412-a33d8ed4-d688-11e7-9a0d-8c599ba7b36d.png)
![git_installed_check](https://user-images.githubusercontent.com/19670372/33480414-a354ef7a-d688-11e7-887d-de3660c2dfe5.png)
![git_not_installed](https://user-images.githubusercontent.com/19670372/33480415-a36af86a-d688-11e7-8180-9b8031e1f6e5.png)
![git_set_env_1](https://user-images.githubusercontent.com/19670372/33480416-a381480e-d688-11e7-9c60-cf644fd83545.png)
![git_set_env_3](https://user-images.githubusercontent.com/19670372/33480417-a3985eea-d688-11e7-8852-8f55cf5a7356.png)
![git_set_env_4](https://user-images.githubusercontent.com/19670372/33480418-a3b0c3fe-d688-11e7-907f-012576d757a1.png)
![gradle_build_command_1](https://user-images.githubusercontent.com/19670372/33480419-a3c9541e-d688-11e7-8adc-b88e537e04ea.png)
![gradle_build_command_2](https://user-images.githubusercontent.com/19670372/33480420-a3e0723e-d688-11e7-9bc0-5e72d968fe9a.png)
![gradle_installation_1](https://user-images.githubusercontent.com/19670372/33480421-a3f702ec-d688-11e7-8a1e-9063e2199fc2.png)
![gradle_installed_check](https://user-images.githubusercontent.com/19670372/33480422-a40da0a6-d688-11e7-8563-396df4d0775d.png)
![gradle_not_installed](https://user-images.githubusercontent.com/19670372/33480423-a424a0c6-d688-11e7-998f-5fc7bce27d74.png)
![gradle_pre_env_screen](https://user-images.githubusercontent.com/19670372/33480424-a43adb8e-d688-11e7-8ab3-c75d8e518e8b.png)
![gradle_run_export_1](https://user-images.githubusercontent.com/19670372/33480425-a45082ae-d688-11e7-8943-921fba383aba.png)
![gradle_run_export_2](https://user-images.githubusercontent.com/19670372/33480426-a46b23d4-d688-11e7-905c-227e5c9a7e45.png)
![gradle_set_env_1](https://user-images.githubusercontent.com/19670372/33480427-a4821364-d688-11e7-84d7-f7a5c772359d.png)
![gradle_set_env_4](https://user-images.githubusercontent.com/19670372/33480428-a498eea4-d688-11e7-96c8-02c0c3419afd.png)
![java_download](https://user-images.githubusercontent.com/19670372/33480429-a4b06124-d688-11e7-8785-a49425571722.png)
![java_installation_1](https://user-images.githubusercontent.com/19670372/33480430-a4c7f154-d688-11e7-8caf-0cbc7ec34a4d.png)
![java_installation_2](https://user-images.githubusercontent.com/19670372/33480431-a4defa84-d688-11e7-90e9-bc8b609c2209.png)
![java_installation_3](https://user-images.githubusercontent.com/19670372/33480432-a4f5c1f6-d688-11e7-86a0-81a79fbf93bb.png)
![java_installation_4](https://user-images.githubusercontent.com/19670372/33480433-a50d238c-d688-11e7-868f-169cfd0f86e9.png)
![java_installed_check](https://user-images.githubusercontent.com/19670372/33480434-a523df32-d688-11e7-953d-f948887cf6d5.png)
![java_not_installed](https://user-images.githubusercontent.com/19670372/33480435-a53ba3ce-d688-11e7-9ea3-ab96bb0a6ca8.png)
![java_set_env_3](https://user-images.githubusercontent.com/19670372/33480436-a553f5aa-d688-11e7-9695-93b9d2c49f1e.png)
![java_set_env_5](https://user-images.githubusercontent.com/19670372/33480437-a572fe6e-d688-11e7-9a2e-a9dc4b615b88.png)
![java_set_variable_path](https://user-images.githubusercontent.com/19670372/33480438-a58eb744-d688-11e7-9e32-1fb7ef77d86d.png)
![os_arc_1](https://user-images.githubusercontent.com/19670372/33480439-a5ab45a8-d688-11e7-9344-d9601b68af68.png)
![os_arc_2](https://user-images.githubusercontent.com/19670372/33480440-a5c25a4a-d688-11e7-8128-2d5e4d8f75a0.png)
![os_arc_3](https://user-images.githubusercontent.com/19670372/33480441-a5d9bfe6-d688-11e7-8a19-251c3e0c4610.png)
![os_arc_cmd_1](https://user-images.githubusercontent.com/19670372/33480442-a5f1af66-d688-11e7-89b9-bc0b9e68fe98.png)
![os_arc_cmd_2](https://user-images.githubusercontent.com/19670372/33480443-a60a6f56-d688-11e7-8e73-a653b45ee583.png)
![pc_properties](https://user-images.githubusercontent.com/19670372/33480444-a622a670-d688-11e7-85de-12be0f054004.png)
![pg_alter_role_tombolo](https://user-images.githubusercontent.com/19670372/33480445-a639d7be-d688-11e7-8e14-7af3fd80e220.png)
![pg_create_ext_tombolo](https://user-images.githubusercontent.com/19670372/33480446-a6517176-d688-11e7-94dc-0ba0dad55fa2.png)
![pg_create_role_tombolo](https://user-images.githubusercontent.com/19670372/33480447-a66bd0f2-d688-11e7-93ee-db8889d0e5a7.png)
![pg_create_tombolo_test_1](https://user-images.githubusercontent.com/19670372/33480448-a6867920-d688-11e7-97ab-1086856d518b.png)
![pg_create_tombolo_test_2](https://user-images.githubusercontent.com/19670372/33480449-a69c291e-d688-11e7-86b4-d894a44df050.png)
![pg_download_1](https://user-images.githubusercontent.com/19670372/33480450-a6c0c742-d688-11e7-9897-0d9e48e93694.png)
![pg_download_2](https://user-images.githubusercontent.com/19670372/33480451-a6d7e968-d688-11e7-8af8-1194e79f6383.png)
![pg_installation_1](https://user-images.githubusercontent.com/19670372/33480452-a6f16ca8-d688-11e7-94d8-f69800d60b30.png)
![pg_installation_4](https://user-images.githubusercontent.com/19670372/33480453-a709d34c-d688-11e7-86bb-136d774a6d30.png)
![pg_installation_7](https://user-images.githubusercontent.com/19670372/33480455-a7222410-d688-11e7-8f31-fd0008cd25c1.png)
![pg_installation_locale_screen_5](https://user-images.githubusercontent.com/19670372/33480456-a73a0bca-d688-11e7-8b7b-327df9acad38.png)
![pg_not_installed](https://user-images.githubusercontent.com/19670372/33480457-a751c300-d688-11e7-801f-e9217cdb0e28.png)
![pg_pre_installation_options_6](https://user-images.githubusercontent.com/19670372/33480458-a769b442-d688-11e7-9509-7d718e1336ac.png)
![pg_sb_1](https://user-images.githubusercontent.com/19670372/33480459-a77fa9b4-d688-11e7-9548-9e433274ac69.png)
![pg_sb_2](https://user-images.githubusercontent.com/19670372/33480460-a796c66c-d688-11e7-8ded-bb6bca9ec4cc.png)
![pg_sb_3](https://user-images.githubusercontent.com/19670372/33480461-a7ad8154-d688-11e7-8e43-855db9cf4930.png)
![pg_sb_16](https://user-images.githubusercontent.com/19670372/33480462-a7c53128-d688-11e7-93c3-5de75c07bc83.png)
![pg_sb_jdbc_4](https://user-images.githubusercontent.com/19670372/33480465-a7dce890-d688-11e7-8a21-15ca035b3ac0.png)
![pg_sb_jdbc_5](https://user-images.githubusercontent.com/19670372/33480466-a7f2f2ac-d688-11e7-862f-82f4457e9db8.png)
![pg_sb_odbc_6](https://user-images.githubusercontent.com/19670372/33480467-a8091f32-d688-11e7-9a22-8643ed793a43.png)
![pg_sb_odbc_7](https://user-images.githubusercontent.com/19670372/33480468-a820a3d2-d688-11e7-8d84-1622527f29e6.png)
![pg_sb_odbc_8](https://user-images.githubusercontent.com/19670372/33480469-a839166a-d688-11e7-84de-4322e5d9cc80.png)
![pg_sb_postgis_9](https://user-images.githubusercontent.com/19670372/33480470-a8534a30-d688-11e7-9690-6c5fa4467017.png)
![pg_sb_postgis_10](https://user-images.githubusercontent.com/19670372/33480471-a86b123c-d688-11e7-9b45-7ac2002071ca.png)
![pg_sb_postgis_11](https://user-images.githubusercontent.com/19670372/33480472-a882231e-d688-11e7-90c5-dfa14235266c.png)
![pg_sb_postgis_12](https://user-images.githubusercontent.com/19670372/33480473-a899534a-d688-11e7-8b73-276a3a2aba35.png)
![pg_sb_postgis_13](https://user-images.githubusercontent.com/19670372/33480474-a8af6680-d688-11e7-903b-db1f7ac394a4.png)
![pg_sb_postgis_14](https://user-images.githubusercontent.com/19670372/33480475-a8c4d6b4-d688-11e7-902d-081b4112981a.png)
![pg_sb_postgis_22](https://user-images.githubusercontent.com/19670372/33480476-a8db63d4-d688-11e7-80cb-28d39fe7b644.png)
![pg_select_component_2](https://user-images.githubusercontent.com/19670372/33480477-a8f74f04-d688-11e7-9fb6-b382b7cfe3f1.png)
![pg_set_env_1](https://user-images.githubusercontent.com/19670372/33480479-a9100508-d688-11e7-8360-e5a9a6b86b3f.png)
![pg_set_env_3](https://user-images.githubusercontent.com/19670372/33480480-a9295102-d688-11e7-8345-be665b7ab077.png)
![pg_tombolo_script](https://user-images.githubusercontent.com/19670372/33480481-a945a49c-d688-11e7-84ab-e4a55e6201cc.png)
![postgres_setup_password_screen_3](https://user-images.githubusercontent.com/19670372/33480482-a95eaaa0-d688-11e7-99a8-a40ad6997124.png)
![rename_project_files](https://user-images.githubusercontent.com/19670372/33480483-a977443e-d688-11e7-88e0-04432ab283d4.png)

**Comment by lorenaqendro** [comment]
Can be closed as the windows tutorial was added by #375.
