### ISSUE TITLE
LatestValueField with  "timeStamp" : false returns dictionary

### ISSUE THREAD

**Issue by thanosbnt** [FutureCitiesCatapult/TomboloDigitalConnector#378]
### Description
geojson export when using LatestValueField and:

  "exporter" : "uk.org.tombolo.exporter.GeoJsonExporter",
  "timeStamp" : false

returns a dictionary of values {"populationDensity": "30.0"}
instead of a value

**Comment by lorenaqendro** [comment]
Closing as the error was produced with an old version on the DC. It'k ok now.
