### ISSUE TITLE
Add gradle task to show importer characteristics

### ISSUE THREAD

**Issue by lorenaqendro** [FutureCitiesCatapult/TomboloDigitalConnector#380]
### Description
The same way as we produce the catalogue we could have a task to get datasourceId, subject types and attributes for a specific importer. This would help the user to get the data needed to build the recipes without getting lost in the long catalogue file, code base or going through the interface.

- [ ] Could be an option to runCatalogue or a different task.
- [ ] Could have a options `-d -s -a` for each element.

**Comment by arya-hemanshu** [comment]
#528 merged
