### ISSUE TITLE
Info on gradle task shows Fetching local file even if the file is currently not stored locally 

### ISSUE THREAD

**Issue by thanosbnt** [FutureCitiesCatapult/TomboloDigitalConnector#381]
### Description
During gradle runExport it is shown INFO  uk.org.tombolo.importer.DownloadUtils - Fetching local file: ... even if the file is not in the \tmp folder. It should print sth like INFO  uk.org.tombolo.importer.DownloadUtils - Downloading file

**Comment by arya-hemanshu** [comment]
Fix merged in Trunk
