### ISSUE TITLE
UI - Calling web developers…we need you!

### ISSUE THREAD

**Issue by eddiejaoude** [FutureCitiesCatapult/TomboloDigitalConnector#399]
From [blog post](http://www.tombolo.org.uk/blog/calling-web-developers-need) ...

![tombolo_pad2](https://user-images.githubusercontent.com/624760/34030468-1b95c09a-e165-11e7-9c66-eb497ed9f4db.png)

## Calling web developers…we need you!

**Calling skilled web developers…come work with us to help build a City Data tool!**

Tombolo is an innovation project, developing products and services to help city authorities better use data to improve the lives of their citizens.

The Digital Connector is an open source piece of software we’ve built, which allows data specialists to efficiently connect data sets into a common format. Users can share the indexes that they create with an open source data community.

We’re looking to appoint a supplier to come work with us to build a cool way of visualising some of the models that we’ve built so far in the Digital Connector for the benefit of Cities.

We’ve got an idea of what we want to build, and we’ve already done the UX in-house.

We’re now looking to work with you to take this to the next step – a fully developed and deployed web-app that users can interact with; that’s built modularly and with scalability in mind; that’s capable of enticing City Decision Makers and an open source community to get behind our open source project.

We’re passionate about the use of data in our cities. If you’ve got a similar passion then please apply [here](https://procontract.due-north.com/Advert?advertId=ffe73b94-bbd6-e711-80e6-005056b64545&p=e6579d4c-914a-e611-8114-000c29c9ba21).

Looking forward to hearing from you,

The Tombolo Project Team

**Comment by lorenaqendro** [comment]
Can be closed as we are already in contact with some potential collaborators. Thank you!
