### ISSUE TITLE
Handling of missing data

### ISSUE THREAD

**Issue by thanosbnt** [FutureCitiesCatapult/TomboloDigitalConnector#408]
### Description
Right now missing data (nan, null etc.) are not been handled. It would be good if the user had the option to either ignore them, fill with averages etc.

**Comment by lorenaqendro** [comment]
The [BackOffField](https://github.com/FutureCitiesCatapult/TomboloDigitalConnector/blob/master/src/main/java/uk/org/tombolo/field/aggregation/BackOffField.java) might help in this case.

See [example](https://github.com/FutureCitiesCatapult/TomboloDigitalConnector/blob/master/src/main/resources/executions/examples/london-cycle-traffic-air-quality-lsoa-backoff.json).
