### ISSUE TITLE
JSON examples improvements

### ISSUE THREAD

**Issue by eddiejaoude** [FutureCitiesCatapult/TomboloDigitalConnector#414]
```
src/main/resources/executions/examples/
```

### Description

Improvements to the json examples:

- Inconsistent spacing e.g. `"fieldClass": ` vs `"subjects" : `
- ~~Inline comments invalidates json, suggest move to local folder `README.md` with code blocks and comments~~
- 1 or 2 extra blank lines between objects not needed

**Comment by theodosiakefala** [comment]
Is this needed? If so I can sort this out :)

**Comment by lorenaqendro** [comment]
@eddiejaoude thanks for creating this issue. Good point!
@theodosiakefala it would be lovely. Thanks!

I wouldn't address the point two though: 

> Inline comments invalidates json, suggest move to local folder README.md with code blocks and comments

The comments are a bit ugly, but they add a good value to understanding better the recipe and what is going on. I would leave them for now. Later on we could think of a better way to index them and maybe document with code blocks the most important and explanatory ones.

**Comment by lorenaqendro** [comment]
Solved in #418.
