### ISSUE TITLE
Documentation filenames to be consistent

### ISSUE THREAD

**Issue by eddiejaoude** [FutureCitiesCatapult/TomboloDigitalConnector#432]
Some file names are hyphenated and some are capitals.

<img width="1018" alt="screenshot 2018-01-12 07 34 19" src="https://user-images.githubusercontent.com/624760/34864220-1d9b648c-f76b-11e7-9908-cce35ab5175c.png">

**Comment by lorenaqendro** [comment]
Very good point, @eddiejaoude!

**Comment by Algogator** [comment]
Can I get assigned to this?

**Comment by ShreejeetaMandal** [comment]
@eddiejaoude / @lorenaqendro ,
Can I be assigned to this?

**Comment by lorenaqendro** [comment]
@ShreejeetaMandal definitely!

**Comment by lorenaqendro** [comment]
@Algogator just realised you had asked for it too. Would you like to get this one?
@ShreejeetaMandal can we assign to @Algogator this one?

**Comment by ShreejeetaMandal** [comment]
Sure!

**Comment by Algogator** [comment]
@lorenaqendro @eddiejaoude Should they all be Capitalized and with hyphens if there are multiple words?

Using-the-Digital-Connector.md ->  	Using-The-Digital-Connector.md 

or 

Using-the-Digital-Connector.md -> UsingTheDigitalConnector.md

**Comment by eddiejaoude** [comment]
My preference would be to use all lowercase to keep it simpler, which would also imply hyphenated (`-` between the words), which would result in... 

```
using-the-digital-connector.md
```

But best for one of the core members like @lorenaqendro to decided 🤓

**Comment by lorenaqendro** [comment]
@Algogator I support Eddie's suggestion, it's simpler. You can go for that.

**Comment by lorenaqendro** [comment]
Closed by #488.
