### ISSUE TITLE
Remove "Project" tab if not used

### ISSUE THREAD

**Issue by eddiejaoude** [FutureCitiesCatapult/TomboloDigitalConnector#444]
The `project` tab reads `0`, if not used, I suggest disabling in the **admin** section. It can always be re-enabled if it is required.

<img width="935" alt="screenshot 2018-01-25 08 03 49" src="https://user-images.githubusercontent.com/624760/35377320-9047e7f4-01a6-11e8-8139-cb4b40b00c06.png">

https://github.com/blog/2339-disabling-projects

**Comment by lorenaqendro** [comment]
Closing as addressed.
<img width="667" alt="screen shot 2018-02-06 at 14 02 45" src="https://user-images.githubusercontent.com/14051876/35863406-7a0f7138-0b46-11e8-800f-ecf6107ca8d3.png">
