### ISSUE TITLE
Class uk.org.tombolo.importer.twitter.TwitterImporterTest failed

### ISSUE THREAD

**Issue by double-u-a** [FutureCitiesCatapult/TomboloDigitalConnector#446]
### Versions

Please provide your platform details:

| Software | Information |
| :--- | :--- |
| Operating System| e.g. `Windows` |
| OS Version| e.g. `10` |
| java -version | e.g. `1.8.0_162` | 
| psql --version | e.g. `10.1` |
| gradle --version | e.g. `4.4.1` |

### Description
On running `gradle test` class uk.org.tombolo.importer.twitter.TwitterImporterTest fails

### Error log

```
org.junit.ComparisonFailure: Value for key (808282128278372352,text) expected:<...as in Marylebone!!! [????????????????] @ Marylebone High S...> but was:<...as in Marylebone!!! [ðŸŽ…ðŸ�½ðŸŽ�ðŸŽ„ðŸŽ…ðŸ�½ðŸŽ�ðŸŽ„] @ Marylebone High S...>
```

**Comment by lorenaqendro** [comment]
Thanks @double-u-a for raising this issue. We’ll have a look at it.
