### ISSUE TITLE
gradle build failed after following steps in issue #465 in windows.

### ISSUE THREAD

**Issue by Divya10** [FutureCitiesCatapult/TomboloDigitalConnector#489]
Software | Information
Operating System | Windows 10 Home
OS Version | 10
java -version | 1.8.0_71
psql --version | 10.2
gradle --version | 4.5

Description:
As per the Windows Installation Guide, after successfully installing all the requirements and building the Digital Connector, we run the runExport command to test. I was facing the same problem that is mentioned in issue #465. I followed the changes advised but now i am facing this error:- method does not override or implement a method from supertype.
Here is the screenshot for the error.

![untitled](https://user-images.githubusercontent.com/17573928/36395283-741249de-15de-11e8-8c4a-dab320beba0e.png)

**Comment by lorenaqendro** [comment]
@Divya10 Please, discard your changes and get the latest version of master as it contains a bug fix for #465.

**Comment by lorenaqendro** [comment]
Let us know, if the latest version works for you, so we can close this issue.

**Comment by Divya10** [comment]
Hi @lorenaqendro ,
I discarded the changes and fetched the latest version of master but i am getting this issue.
![untitled](https://user-images.githubusercontent.com/17573928/36425618-5617548a-166d-11e8-9d61-d629c60a68d9.png)

**Comment by lorenaqendro** [comment]
@Divya10 Can you please remove the comments from the json recipe before running? The parser is complaining about them.

**Comment by Divya10** [comment]
@lorenaqendro  thank you it worked.
