### ISSUE TITLE
Output file not created in macOS

### ISSUE THREAD

**Issue by anchal0997** [FutureCitiesCatapult/TomboloDigitalConnector#501]
Operating System : MacOS
OS version : 10.13.3
Java version : 1.8.0_131
psql version : 10.2
gradle version : 4.5.1

Software versions in the [Let's start](/README.md#lets-start) section in the README.

### Description

An output file should be generated after running the command `gradle runExport -Precipe='src/main/resources/executions/examples/reaggregate-traffic-count-to-la.json'` but no output file was generated.
There wasn't any error. 
![screen shot 2018-02-23 at 11 57 53 am](https://user-images.githubusercontent.com/21989049/36581083-29e6ffd4-1891-11e8-8371-66858e35ec18.png)

**Comment by lorenaqendro** [comment]
Please specify also the output file through the `-Poutput` option.
Try to run `gradle runExport -Precipe='src/main/resources/executions/examples/reaggregate-traffic-count-to-la.json' -Poutput='reaggregate-output.json'`, but before running it remove the comments in the json recipe `src/main/resources/executions/examples/reaggregate-traffic-count-to-la.json`.

**Comment by anchal0997** [comment]
Still the output file is not generated.
The output of `gradle runExport -Precipe='src/main/resources/executions/examples/reaggregate-traffic-count-to-la.json' -Poutput='reaggregate-output.json'` is attached below.

[_output.txt](https://github.com/FutureCitiesCatapult/TomboloDigitalConnector/files/1751408/_output.txt)

**Comment by lorenaqendro** [comment]
@anchal0997 Can you check if this problem still persists for you. We cannot replicate it.

**Comment by lorenaqendro** [comment]
Closing the issue as not reported again back again.
