### ISSUE TITLE
password authentication failed postgresql

### ISSUE THREAD

**Issue by davidkazemzadeh** [FutureCitiesCatapult/TomboloDigitalConnector#546]
### Versions

Please provide your platform details:

| Software | Information |
| :--- | :--- |
| Operating System| `Windows` |
| OS Version| `16299.309` |
| java -version | `1.8.0_151` | 
| psql --version | `10` |
| gradle --version | `4.6.1` |

Software versions in the [Let's start](/README.md#lets-start) section in the README.

### Description

Attempting to enter 'tombolo' password after executing -- psql -d tombolo -U tombolo < src\main\resources\sql\create_database.sql -- to set up database.

However, password authentication is failing.

### Error log

```
psql: FATAL:  password authentication failed for user "tombolo"
```

**Comment by lorenaqendro** [comment]
@davidkazemzadeh thank you for rising this issue. I believe this was solved during the hackathon by restarting the OS.
